openapi: 3.0.0
info:
  title: Felhasználó API
  version: 1.0.0
  description: Egyszerű REST API felhasználók létrehozására és listázására

servers:
  - url: http://localhost:3000/api

paths:
  /users:
    get:
      summary: Felhasználók listázása
      responses:
        '200':
          description: Sikeres válasz
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'

    post:
      summary: Új felhasználó létrehozása
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: Sikeres létrehozás
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Hibás kérés

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email

    NewUser:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string